### ISSUE TITLE
Why Ansible?

### ISSUE THREAD

**Issue by OctavioBR** [thiagocaiubi/macos#1]
Looking at your playbook looks like you (wisely) managed to keep almost all installs using homebrew.  
I'd suggest for you to use only git→bash→homebrew as tools for setting up your machine. You may `brew bundle dump` to generate a `Brewfile` which eases keeping up-to-date on what to install.

Reference: https://github.com/Homebrew/homebrew-bundle

**Comment by thiagocaiubi** [comment]
Hey @OctavioBR, sorry for my late response.

Thanks for bringing this up. When I started the project, I didn't know about Homebrew's bundle feature. After some time, a colleague asked me the same question. This is a toy project and is likely to have bad decisions 😄. I'm also using Ansible to setup a few macOS configurations. Please see https://github.com/thiagocaiubi/macos/blob/63cf943f95395bdd991e5a6435126bd95ba2bac3/main.yml#L82-L102. 
I will likely keep using Ansible to set up other things at the filesystem level, for example. 
Anyway, thanks again for bringing this up to my attention. I will look closer at Homebrew's bundle feature when I have the time.

**Comment by OctavioBR** [comment]
Absolutely mate, brew bundle was just a suggestion to make the package management a bit more handy. Ansible's [osx_defaults](https://docs.ansible.com/ansible/latest/collections/community/general/osx_defaults_module.html) module is very neat. Keep it up 😅
